title: "NBA Finals"
author: your mom
email: your-mom@domain.com
description: > # this means to ignore newlines until "baseurl:"
  your mom is a nba fan and she slept with your father u loser.get a job.
theme: minima
# social links
twitter_username: yourmom # DO NOT include the @ character, or else the build will fail!
github_username:  yourmom # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
